export const FIELD_INFO = {
  Joueurs: "Player name. Click to open the full player card.",
  Gardiens: "Goalie name. Click to open the full player card.",
  Team: "Team abbreviation. Click to open the team's line combinations on Daily Faceoff (new tab).",
  Position: "Position: Center (C), Left Wing (L), Right Wing (R), Defence (D) or Goaltender (G).",
  GP: "Games played.",
  G: "Goals.",
  A: "Assists.",
  P: "Points (goals + assists).",
  "+/-": "Plus/minus: goals for minus goals against at even strength while the player is on the ice.",
  PPP: "Power play points: goals plus assists scored while the team is on the power play.",
  TOI: "Average time on ice per game (minutes:seconds).",
  Age: "Age at the start of the season (October 1st).",
  RVI: "Relative Value Index: weighted composite of G, A, P, +/-, PPP (vs league average), games played and age, computed against the currently filtered positions. Its value changes with the position filter. Higher is better.",
  GVI: "General Value Index: weighted composite of stats (G, A, P, +/-, PPP vs league average, games played and age for skaters; W, SV%, GAA and GP for goalies). Always the same regardless of the current position filter. Higher is better.",
  AGVI: "Average GVI across the available seasons: an indicator of a player's typical year-over-year value.",
  RotoVal: "Z-score: sum of each category's standard deviations above/below the league average. Higher is better.",
  "RotoVal-Pos": "Roto Z-score against players of the same group (Forwards / Defence).",
  "RotoVal-PosExact": "Roto Z-score against players of the exact same position (C, L, R or D).",
  "RotoVal-Pace": "Z-score of each category projected over an 82-game pace.",
  PM82: "Plus/minus projected over an 82-game pace.",
  G82: "Goals projected over an 82-game pace.",
  A82: "Assists projected over an 82-game pace.",
  P82: "Points projected over an 82-game pace.",
  PPP82: "Power play points projected over an 82-game pace.",
  W82: "Wins projected over an 82-game pace.",
  W: "Wins.",
  "SV%": "Save percentage: saves divided by shots faced.",
  GAA: "Goals against average: goals allowed per 60 minutes. Lower is better.",
  rankG: "League rank in goals.",
  rankA: "League rank in assists.",
  rankP: "League rank in points.",
  rankPPP: "League rank in power play points.",
  rankPM: "League rank in plus/minus.",
  rankW: "League rank in wins.",
  rankSV: "League rank in save percentage.",
  rankGAA: "League rank in goals against average (lower is better).",
  Rank: "League rank for the category (e.g. 3/320 means 3rd of 320 players).",
  Z: "Z-score: sum of each category's standard deviations above/below the league average. Higher is better.",
  ZP: "Roto Z-score against players of the same group (Forwards / Defence).",
  ZPX: "Roto Z-score against players of the exact same position (C, L, R or D).",
  Z82: "Z-score of each category projected over an 82-game pace.",
  "Avg TOI": "Average time on ice per game.",
  L: "Losses.",
  OTL: "Overtime or shootout losses.",
  SO: "Shutouts.",
  PPG: "Power play goals.",
  Opp: "Opponent team.",
  "W/L": "Goalie decision: Win, Loss or Overtime loss.",
  Season: "Season (start year - end year).",
  Date: "Game date.",
};

export const SECTION_INFO = {
  currentSeason: "Stats for the current regular season.",
  career: "Career totals across all NHL regular seasons.",
  seasons: "Year-by-year stats for each season available in the season selector.",
  last5: "The player's last 5 games played.",
  progression: "Chart of each category across the seasons shown above. Use the dropdown to chart a single season; the button toggles between cumulative totals and per-game values.",
  awards: "Trophies and honors won during the player's career.",
  comparison: "Side-by-side comparison of the selected players.",
  stats: "Season stats for the selected players. The best value in each row is bolded.",
  radar: "Per-category z-scores for the selected players. Use the dropdown to choose the reference pool (compared players, same position group or all players).",
};